// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: notebar.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Notebar.gRPC {
  public static partial class NotebarService
  {
    static readonly string __ServiceName = "notebar.NotebarService";

    static readonly grpc::Marshaller<global::Notebar.gRPC.AddIndicatorRequest> __Marshaller_notebar_AddIndicatorRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Notebar.gRPC.AddIndicatorRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Notebar.gRPC.AddIndicatorResponse> __Marshaller_notebar_AddIndicatorResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Notebar.gRPC.AddIndicatorResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Notebar.gRPC.AddIndicatorRequest, global::Notebar.gRPC.AddIndicatorResponse> __Method_AddIndicator = new grpc::Method<global::Notebar.gRPC.AddIndicatorRequest, global::Notebar.gRPC.AddIndicatorResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddIndicator",
        __Marshaller_notebar_AddIndicatorRequest,
        __Marshaller_notebar_AddIndicatorResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Notebar.gRPC.NotebarReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NotebarService</summary>
    public abstract partial class NotebarServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Notebar.gRPC.AddIndicatorResponse> AddIndicator(global::Notebar.gRPC.AddIndicatorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NotebarService</summary>
    public partial class NotebarServiceClient : grpc::ClientBase<NotebarServiceClient>
    {
      /// <summary>Creates a new client for NotebarService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NotebarServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NotebarService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NotebarServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NotebarServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NotebarServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Notebar.gRPC.AddIndicatorResponse AddIndicator(global::Notebar.gRPC.AddIndicatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddIndicator(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Notebar.gRPC.AddIndicatorResponse AddIndicator(global::Notebar.gRPC.AddIndicatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddIndicator, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Notebar.gRPC.AddIndicatorResponse> AddIndicatorAsync(global::Notebar.gRPC.AddIndicatorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddIndicatorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Notebar.gRPC.AddIndicatorResponse> AddIndicatorAsync(global::Notebar.gRPC.AddIndicatorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddIndicator, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NotebarServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NotebarServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NotebarServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddIndicator, serviceImpl.AddIndicator).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NotebarServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddIndicator, serviceImpl.AddIndicator);
    }

  }
}
#endregion
