//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteBar.App.NoteBarServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoteBarServiceReference.INoteBarService")]
    public interface INoteBarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteBarService/AddIndicator", ReplyAction="http://tempuri.org/INoteBarService/AddIndicatorResponse")]
        string AddIndicator(uint port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteBarService/AddIndicator", ReplyAction="http://tempuri.org/INoteBarService/AddIndicatorResponse")]
        System.Threading.Tasks.Task<string> AddIndicatorAsync(uint port);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INoteBarServiceChannel : NoteBar.App.NoteBarServiceReference.INoteBarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoteBarServiceClient : System.ServiceModel.ClientBase<NoteBar.App.NoteBarServiceReference.INoteBarService>, NoteBar.App.NoteBarServiceReference.INoteBarService {
        
        public NoteBarServiceClient() {
        }
        
        public NoteBarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoteBarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteBarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteBarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddIndicator(uint port) {
            return base.Channel.AddIndicator(port);
        }
        
        public System.Threading.Tasks.Task<string> AddIndicatorAsync(uint port) {
            return base.Channel.AddIndicatorAsync(port);
        }
    }
}
